Repository microsoft/FactoryOrchestrator, pull requests merged in 2021-03, with the labels that each got.

#96 Release build pushes NuGet & PSGallery packages
  build/release-pipeline.yml
  build/templates/template-push-vpack-other.yml
  build/templates/template-push-vpack-service.yml
  build/templates/template-set-initial-variables.yml
  build/templates/template-set-should-push.yml
  build/templates/template-set-should-sign.yml
Labels: QOL, build

#97 Improve ClientSampleIntegrationTest for better failure fingerprinting
  src/ClientSample/Program.cs
  src/Tests/ClientSampleIntegrationTest/ClientSampleIntegrationTests.cs
Labels: QOL, test code

#98 fix yml indentation
  build/release-pipeline.yml
Labels: build

#100 Fix broken links; Improve overview page
  README.md
  docs/docs/factory-orchestrator-client-usage-samples.md
  docs/docs/get-started-with-factory-orchestrator.md
  docs/docs/index.md
  docs/docs/service-configuration.md
  docs/docs/tasks-and-tasklists.md
  docs/docs/use-the-factory-orchestrator-api.md
  docs/docs/use-the-factory-orchestrator-app.md
Labels: bug, documentation

#105 add some pics; link to video
  docs/docs/get-started-with-factory-orchestrator.md
  docs/docs/images/service-start.png
  docs/docs/index.md
Labels: documentation

#104 Command Line tab in UWP app stores command history
  src/App/ConsolePage.xaml
  src/App/ConsolePage.xaml.cs
Labels: enhancement

#103 AppxManifest is autogenerated as obj file
  build/SetSourceVersion.ps1
  src/App/DevPackage.appxmanifest
  src/App/Microsoft.FactoryOrchestrator.App.csproj
  src/App/Package.appxmanifest
Labels: build

#110 Only require EnableNetworkAccess; Rename log folder setting for clarity
  src/Service/ServiceExe.cs
Labels: QOL

#106 Enabled SSL encryption for Factory Orchestrator Service.
  build/config/CredScanSuppressions.json
  docs/docs/ClientLibrary/Microsoft-FactoryOrchestrator-Client-FactoryOrchestratorClient-CallBack.md
  docs/docs/ClientLibrary/Microsoft-FactoryOrchestrator-Client-FactoryOrchestratorClient-CertificateHash.md
  docs/docs/ClientLibrary/Microsoft-FactoryOrchestrator-Client-FactoryOrchestratorClient-FactoryOrchestratorClient(System-Net-IPAddress_System-Net-Security-RemoteCertificateValidationCallback_int_string).md
  docs/docs/ClientLibrary/Microsoft-FactoryOrchestrator-Client-FactoryOrchestratorClient-FactoryOrchestratorClient(System-Net-IPAddress_System-Net-Security-RemoteCertificateValidationCallback_int_string_string).md
  docs/docs/ClientLibrary/Microsoft-FactoryOrchestrator-Client-FactoryOrchestratorClient-FactoryOrchestratorClient(System-Net-IPAddress_int_string_string).md
  docs/docs/ClientLibrary/Microsoft-FactoryOrchestrator-Client-FactoryOrchestratorClient-ServerCertificateValidationCallback.md
  docs/docs/ClientLibrary/Microsoft-FactoryOrchestrator-Client-FactoryOrchestratorClient-ServerIdentity.md
  docs/docs/ClientLibrary/Microsoft-FactoryOrchestrator-Client-FactoryOrchestratorClient.md
  src/App/ConnectionPage.xaml
  src/App/ConnectionPage.xaml.cs
  src/App/Resources/en-US/Resources.resw
  src/ClientLibrary/FactoryOrchestratorClient.cs
  src/CoreLibrary/Resources/Resources.Designer.cs
  src/CoreLibrary/Resources/Resources.resx
  src/PowerShellLibrary/FactoryOrchestratorClientSync.cs
  src/Service/FactoryServer.pfx
  src/Service/Microsoft.FactoryOrchestrator.Service.csproj
  src/Service/ServiceExe.cs
  src/UWPClientLibrary/FactoryOrchestratorUWPClient.cs
Labels: enhancement
