Repository microsoft/FactoryOrchestrator, pull requests merged in 2021-07, with the labels that each got.

#170 Fixing fastpass bugs on tasklist and connection pages
  src/App/EditPage.xaml
  src/App/Resources/en-US/Resources.resw
  src/App/SaveLoadEditPage.xaml
Labels: bug

#169 Win UI 3 Update and Enhanced Navigation
  README.md
  src/App/AboutPage.xaml
  src/App/App.xaml
  src/App/AppsPage.xaml
  src/App/ConsolePage.xaml
  src/App/FileTransferPage.xaml
  src/App/MainPage.xaml
  src/App/MainPage.xaml.cs
  src/App/Microsoft.FactoryOrchestrator.App.csproj
  src/App/SaveLoadEditPage.xaml
  src/App/TaskListExecutionPage.xaml
  src/UWPClientLibrary/Microsoft.FactoryOrchestrator.UWPClient.csproj
Labels: bug, dependencies, enhancement

#172 An element is focused through the entire main page taborder
  src/App/EditPage.xaml
  src/App/MainPage.xaml
Labels: bug

#173 Made console error ouput WCAG 2.2 compliant by ensuring a contrast ratio of 4.5 or higher
  src/App/ConsolePage.xaml.cs
Labels: bug

#174 Make EditPage and MainPage responsive and enable future efforts
  src/App/App.xaml
  src/App/EditPage.xaml
  src/App/MainPage.xaml
Labels: bug, enhancement

#175 Made console scrollable by keyboard and adjusted the layout
  src/App/ConsolePage.xaml
Labels: bug

#178 Runtasklistbugfixes
  src/App/EditPage.xaml
  src/App/EditPage.xaml.cs
  src/App/ResultsPage.xaml
Labels: bug
